services:
  - type: web
    name: your-service-name 
    env: python
    pythonVersion: "3.11"
    systemPackages:
      - name: libreoffice-writer # For DOCX
      - name: libreoffice-calc # If you ever need spreadsheet conversion
      - name: libreoffice-impress # For presentations
      - name: libreoffice-common
      - name: unoconv # Install the unoconv utility script itself
      # - name: fonts-liberation # Recommended for good font compatibility
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn app:app --timeout 120"
    # ... envVars ...